### ISSUE TITLE
b:undo_ftplugin not set in filetype plugin

### ISSUE THREAD

**Issue by dkearns** [krischik/vim-ada#21]
All filetype plugins should set `b:undo_ftplugin` to a command string that, when evaluated upon a filetype change, undoes any configuration changes made by the plugin.

See `:help undo_ftplugin` for details and [examples](https://github.com/vim/vim/search?q=b%3Aundo_ftplugin) in the distribution.

**Comment by krischik** [comment]
What does it do? Or is that just another thing you blindly add to a VimScript not knowing what it is good for?

**Comment by krischik** [comment]
I'll guess I'll add it when I find time.

**Comment by dkearns** [comment]
You can assign it to me if you like.

**Comment by krischik** [comment]
Sure. Adding features you don't know what they do is always a bit flaky.
